### PR TITLE
Fix color of gold amount in story pages

### LINKED ISSUE #2173: Text-Color issue for Gold in post-match Story
**Current Behavior**
Hello, when you look at the **Story** of the post-match the **Gold** is text colored in Black with a dark background making it very difficult te read.

Capture

**Expected behavior/code**
Gold text should use a yellow colored value.

**Environment**
- Browser Version: Brave (0.67.124) based on Chromium: 76.0.3809.100
- OS: Windows 10

Regards,

### PR DESCRIPTION
**Pull request by 102**
fixes #2173

### CODE REVIEW

File: src/components/Match/MatchStory.jsx [hunk 1]
```diff
@@ -29,7 +29,9 @@ const GoldSpan = (amount) => {
   const { strings } = store.getState().app;
   return (
     <StyledStorySpan key={`gold_${amount}`}>
-      <font color={constants.colorGolden}>{amount.toLocaleString()}</font>
```
Comment (102) [inline src/components/Match/MatchStory.jsx]: image

[source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font)
