### PR TITLE
Fix body layout to prevent white offset when tooltips were opened once

### LINKED ISSUE #2386: White gap under the footer after settings dropdown being open
**Current Behavior**
When I open settings dropdown in header (screenshot in details), and close it after that, I can see the white gap below the footer (screenshot is attached as well).

**Expected behavior/code**
The gap should not appear

**Console Output**
There's no output in console

**Environment**
- Browser Version: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- OS: Windows 10

**Possible Solution**
I have no solution for the moment

**Additional context/Screenshots**
<details>
<summary>Related screenshots</summary>

Header options button:
image

The gap:
image
</details>

### PR DESCRIPTION
**Pull request by bdbch**
This PR fixes #2386 - it adds some necessary css attributes to the body element so it doesn't cause this strange bug to appear when using `display: initial`. I also fixed some issues with the home page layout having a buggy offset.

(The text wasn't centered on the background image)

---

Additional: Since I use prettier for all of my work I added a prettier-config and a helper package that sets up prettier to work with eslint.

### CODE REVIEW

File: src/components/App/App.jsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ import Matches from '../Matches';
 import Meta from '../Meta';
 import Player from '../Player';
 import Predictions from '../Predictions';
-// import Assistant from '../Assistant';
+// import Assistant from "../Assistant";
```
Comment (howardchung) [inline src/components/App/App.jsx:24]: lol not sure why it did this, but fine
